# -*- coding: utf-8 -*-
# Bilingual article data. Each article: id, date, pl/en -> slug, title, desc, lead, sections[(h2, [paragraphs])]
DATE = "2026-10-04"
ARTS = [
 dict(id="co-to-jest", date=DATE,
  pl=dict(slug="matchmaking-po-polsku-dla-kogo", title="Matchmaking po polsku: czym jest i dla kogo jest przeznaczony",
   desc="Czym jest prywatny matchmaking, jak działa swatka i komu może pomóc. Praktyczny przewodnik dla Polaków mieszkających w Londynie i w Wielkiej Brytanii.",
   lead="Matchmaking to starsza i bardziej osobista idea, niż mogłoby się wydawać: zamiast samodzielnie przeglądać profile, powierza Pan/Pani poszukiwania człowiekowi, który pozna Pana/Panią naprawdę.",
   sections=[
    ("Czym jest prywatny matchmaking", ["Prywatny matchmaking to usługa, w której swatka poznaje Pana/Pani oczekiwania, wartości i styl życia, a następnie szuka osób, które do nich pasują. Nie jest to katalog profili ani algorytm. Za każdym dopasowaniem stoi rozmowa i ludzka ocena.",
      "Dobra swatka nie obiecuje cudów. Jej zadaniem jest zaoszczędzić Panu/Pani czasu, który inaczej poszedłby na spotkania z osobami, które od początku nie miały szans być właściwe."]),
    ("Dlaczego „po polsku”", ["Dla wielu osób o polskich korzeniach rozmowa o związkach, rodzinie i oczekiwaniach jest naturalniejsza w ojczystym języku. Wspólny kontekst kulturowy, od tradycji świątecznych po podejście do rodziny, pomaga szybciej wyjaśnić, czego Pan/Pani szuka.",
      "W Dobrani rozmowy prowadzone są po polsku lub po angielsku, zależnie od Pana/Pani preferencji, a poszukiwania obejmują Londyn i całą Wielką Brytanię."]),
    ("Dla kogo jest matchmaking", ["Najczęściej korzystają z niego osoby zapracowane, które nie chcą poświęcać wieczorów na aplikacje, a także te, które mają już za sobą rozczarowania i szukają poważnego związku. Pomaga również osobom, które cenią dyskrecję i wolą nie wystawiać swojego profilu na publiczny przegląd.",
      "Jeśli nie jest Pan/Pani pewien/pewna, czy to właściwa droga, pierwsza rozmowa jest bezpłatna i niezobowiązująca. To dobra okazja, by zadać pytania i samodzielnie ocenić, czy takie podejście odpowiada Panu/Pani."]),
    ("Jak wygląda współpraca", ["Zaczyna się od rozmowy wstępnej, potem następuje przemyślane dopasowanie, a na końcu dyskretne przedstawienie. Szczegóły opisaliśmy na stronie „Jak to działa”."])]),
  en=dict(slug="polish-matchmaking-who-is-it-for", title="Polish Matchmaking: What It Is and Who It Is For",
   desc="What private matchmaking is, how a matchmaker works and who it can help. A practical guide for Poles living in London and across the UK.",
   lead="Matchmaking is an older and more personal idea than it may seem: instead of browsing profiles alone, you entrust the search to someone who gets to know you properly.",
   sections=[
    ("What private matchmaking is", ["Private matchmaking is a service in which a matchmaker learns your expectations, values and lifestyle, then looks for people who genuinely fit them. It is not a catalogue of profiles or an algorithm. Behind every introduction there is a conversation and human judgement.",
      "A good matchmaker does not promise miracles. Her job is to save you the time you would otherwise spend meeting people who were never likely to be right."]),
    ("Why “Polish”", ["For many people with Polish roots, talking about relationships, family and expectations feels more natural in their first language. A shared cultural context, from holiday traditions to attitudes towards family, helps you explain what you are looking for more quickly.",
      "At Dobrani, conversations are held in Polish or English, whichever you prefer, and the search covers London and the whole UK."]),
    ("Who matchmaking is for", ["It is most often used by busy people who do not want to spend their evenings on apps, and by those who have been disappointed before and are looking for a serious relationship. It also suits people who value discretion and prefer not to put their profile on public display.",
      "If you are not sure it is the right route, the first conversation is free and without obligation. It is a good chance to ask questions and judge for yourself whether the approach suits you."]),
    ("What working together looks like", ["It begins with an initial conversation, followed by thoughtful matching and, finally, a discreet introduction. We describe each step on the “How it works” page."])])),
 dict(id="londyn", date=DATE,
  pl=dict(slug="randki-w-londynie-dla-polakow", title="Randki w Londynie dla Polaków: dlaczego aplikacje nie zawsze wystarczają",
   desc="Jak szukać partnera jako Polak lub Polka w Londynie i dlaczego aplikacje randkowe nie zawsze się sprawdzają. Wskazówki i alternatywa w postaci matchmakingu.",
   lead="Londyn to miasto ogromnych możliwości, ale poznanie kogoś, kto naprawdę pasuje, bywa tu zaskakująco trudne.",
   sections=[
    ("Duże miasto, mało czasu", ["Wiele osób, które przeprowadziły się do Londynu, pracuje intensywnie i ma niewiele czasu na życie towarzyskie. Dojazdy, praca i obowiązki sprawiają, że okazji do spokojnego poznania kogoś jest mniej, niż można by sądzić.",
      "Aplikacje obiecują wygodę, ale przeglądanie profili i prowadzenie wielu rozmów naraz samo w sobie zajmuje czas i energię."]),
    ("Brak wspólnego kontekstu", ["Osoby, które wychowały się w Polsce lub w polskiej rodzinie, często szukają kogoś, kto rozumie ich wartości i tło kulturowe. Aplikacje rzadko pozwalają to ocenić na wczesnym etapie, dlatego łatwo spotykać się z kimś, z kim brakuje podstawowego porozumienia.",
      "Nie oznacza to, że partner musi być Polakiem. Chodzi o to, by świadomie ocenić, co jest dla Pana/Pani ważne."]),
    ("Zmęczenie aplikacjami", ["Częstym doświadczeniem jest poczucie, że rozmowy urywają się bez wyjaśnienia, a spotkania nie prowadzą do niczego trwałego. Po jakimś czasie wiele osób zaczyna szukać innego sposobu.",
      "Jednym z nich jest matchmaking: osobista rozmowa, przemyślane dopasowanie i przedstawienie osoby, która jest poważnie nastawiona na związek."]),
    ("Co można zrobić", ["Warto jasno określić, czego Pan/Pani szuka, i rozważyć, czy samodzielne poszukiwania nadal Panu/Pani służą. Jeśli chce Pan/Pani porozmawiać o alternatywie, zapraszamy na bezpłatną, poufną rozmowę."])]),
  en=dict(slug="dating-in-london-for-poles", title="Dating in London as a Pole: Why Apps Are Not Always Enough",
   desc="How to look for a partner as a Pole in London, and why dating apps do not always work. Practical thoughts and matchmaking as an alternative.",
   lead="London is a city of enormous possibility, yet meeting someone who truly fits can be surprisingly hard.",
   sections=[
    ("A big city and little time", ["Many people who have moved to London work long hours and have little time for a social life. Commuting, work and everyday obligations mean there are fewer chances to meet someone in a relaxed way than you might expect.",
      "Apps promise convenience, but browsing profiles and keeping several conversations going at once takes its own time and energy."]),
    ("No shared context", ["People who grew up in Poland or in a Polish family often look for someone who understands their values and cultural background. Apps rarely let you judge that early on, so it is easy to meet someone with whom there is no basic common ground.",
      "That does not mean a partner must be Polish. It means being clear about what matters to you."]),
    ("App fatigue", ["It is a common experience that conversations fade without explanation and dates lead nowhere lasting. After a while, many people start looking for another way.",
      "One option is matchmaking: a personal conversation, thoughtful matching and an introduction to someone who is serious about a relationship."]),
    ("What you can do", ["It helps to define clearly what you are looking for and to ask whether searching alone is still working for you. If you would like to talk about an alternative, you are welcome to book a free, confidential conversation."])])),
 dict(id="pierwsza-rozmowa", date=DATE,
  pl=dict(slug="pierwsza-rozmowa-ze-swatka", title="Pierwsza rozmowa ze swatką: czego się spodziewać",
   desc="Jak wygląda pierwsza, bezpłatna rozmowa ze swatką, jakie pytania warto zadać i jak się przygotować. Matchmaking po polsku w Londynie i UK.",
   lead="Pierwsza rozmowa to okazja, by się poznać i sprawdzić, czy ten sposób szukania partnera jest dla Pana/Pani.",
   sections=[
    ("To rozmowa, nie przesłuchanie", ["Celem spotkania jest zrozumienie, kim Pan/Pani jest i czego szuka. Rozmowa przebiega w spokojnej atmosferze, po polsku lub po angielsku, i jest w pełni poufna.",
      "Nie trzeba się specjalnie przygotowywać. Wystarczy szczerość."]),
    ("Czego swatka będzie chciała się dowiedzieć", ["Zwykle pytam o styl życia, wartości, doświadczenia z dotychczasowych relacji oraz o to, jak wyobraża sobie Pan/Pani wspólną przyszłość. Ważne są także rzeczy praktyczne, takie jak miejsce zamieszkania czy to, jak wygląda Pana/Pani tydzień.",
      "Te informacje pozwalają mi szukać osób, które pasują nie tylko na papierze."]),
    ("Pytania, które warto zadać", ["Warto zapytać, jak wygląda proces, ile trwa dopasowanie, jak chroniona jest Pana/Pani prywatność oraz jakie są dostępne członkostwa. Dobra swatka odpowiada otwarcie i bez presji.",
      "Informacje o członkostwach znajdzie Pan/Pani także na stronie z ofertą."]),
    ("Co dalej", ["Po rozmowie sam/sama decyduje Pan/Pani, czy chce kontynuować. Pierwsza rozmowa jest bezpłatna i niezobowiązująca."])]),
  en=dict(slug="first-conversation-with-a-matchmaker", title="Your First Conversation with a Matchmaker: What to Expect",
   desc="What the first, free conversation with a matchmaker looks like, which questions to ask and how to prepare. Polish matchmaking in London and the UK.",
   lead="The first conversation is a chance to get to know each other and see whether this way of finding a partner suits you.",
   sections=[
    ("A conversation, not an interrogation", ["The aim is to understand who you are and what you are looking for. It takes place in a relaxed setting, in Polish or English, and is completely confidential.",
      "There is no need to prepare in any special way. Honesty is enough."]),
    ("What a matchmaker will want to know", ["I usually ask about lifestyle, values, experiences in past relationships and how you picture a shared future. Practical things matter too, such as where you live and what your week looks like.",
      "This helps me look for people who fit you in more than just on paper."]),
    ("Questions worth asking", ["It is worth asking how the process works, how long matching takes, how your privacy is protected and what memberships are available. A good matchmaker answers openly and without pressure.",
      "You can also find membership information on the services page."]),
    ("What happens next", ["After the conversation, the decision to continue is yours. The first conversation is free and without obligation."])])),
 dict(id="swatka-czy-aplikacja", date=DATE,
  pl=dict(slug="swatka-czy-aplikacja-randkowa", title="Swatka czy aplikacja randkowa: jak wybrać właściwą drogę",
   desc="Porównanie matchmakingu i aplikacji randkowych: czas, prywatność, jakość dopasowań i koszty. Jak wybrać drogę, która pasuje do Pana/Pani.",
   lead="Obie drogi mają swoje miejsce. Pytanie brzmi, która lepiej odpowiada Pana/Pani sytuacji.",
   sections=[
    ("Czas i zaangażowanie", ["Aplikacje wymagają regularnej uwagi: przeglądania profili, odpowiadania na wiadomości, organizowania spotkań. Swatka przejmuje większość tej pracy, a Pan/Pani spotyka się z osobami wcześniej dobranymi.",
      "Dla osób o napiętym grafiku może to być istotna różnica."]),
    ("Prywatność", ["Profil w aplikacji bywa widoczny dla wielu osób. W matchmakingu dane są poufne i nie są udostępniane bez zgody, co ma znaczenie dla osób ceniących dyskrecję."]),
    ("Jakość dopasowań", ["Aplikacja opiera się na filtrach i własnej ocenie użytkowników. Swatka dodaje do tego rozmowę i osobisty osąd, a także weryfikuje osoby, które przedstawia. Żadna metoda nie gwarantuje wyniku, ale podejście osobiste pozwala uwzględnić rzeczy, których formularz nie uchwyci."]),
    ("Koszty", ["Aplikacje są zwykle tańsze albo bezpłatne, matchmaking jest usługą indywidualną i kosztuje więcej. Warto ocenić, ile czasu i energii kosztują Pana/Panią dotychczasowe poszukiwania.",
      "Jeśli chce Pan/Pani zacząć od czegoś lżejszego, dostępne jest bezpłatne członkostwo w sieci singli. Szczegóły znajdzie Pan/Pani na stronie z ofertą."])]),
  en=dict(slug="matchmaker-or-dating-app", title="Matchmaker or Dating App: How to Choose the Right Route",
   desc="Matchmaking compared with dating apps: time, privacy, quality of introductions and cost. How to choose the route that suits you.",
   lead="Both routes have their place. The question is which one better fits your situation.",
   sections=[
    ("Time and effort", ["Apps need regular attention: browsing profiles, replying to messages, arranging dates. A matchmaker takes over most of that work, and you meet people who have already been carefully selected.",
      "For anyone with a full schedule, that can make a real difference."]),
    ("Privacy", ["An app profile can be visible to many people. In matchmaking your details are confidential and are not shared without consent, which matters to those who value discretion."]),
    ("Quality of introductions", ["An app relies on filters and users’ own judgement. A matchmaker adds a conversation and personal judgement, and vets the people she introduces. No method guarantees an outcome, but a personal approach can take into account things a form cannot capture."]),
    ("Cost", ["Apps are usually cheaper or free, while matchmaking is an individual service and costs more. It is worth weighing how much time and energy your search has cost you so far.",
      "If you would rather start with something lighter, free membership of the singles network is available. You will find the details on the services page."])])),
]
